### ISSUE TITLE
Admin user / password

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-docs#1]
Documentation here state to use **Admin** as username & any password.
I am unable to login following this method (I am brought back to the login page)  debug tools states 401 unauthorized error.

https://github.com/ironmansoftware/universal-docs/blob/master/getting-started.md

Either the documentation is incorrect and an actual password is needed (which is my assumption and why I opened the issue here) or something else is going on.

**Comment by adamdriscoll** [comment]
I think this was a bug with our login process. The default user name is admin and no password. Can you verify that you're still having an issue on 1.2.2?

**Comment by itfranck** [comment]
@adamdriscoll A password is absolutely required (no password won't work since the field is mandatory) but as opposed to before, entering any string as the password do not return a 401 error anymore. Documentation is accurate and process work as expected for me in 1.2
