### ISSUE TITLE
commit 6b9685b8b589927816f9f0639c51dc1abf15bee1 overwrote updates from f9bbd5b16eec8502456cad78419a36af3172a317

### ISSUE THREAD

**Issue by rbleattler** [ironmansoftware/universal-docs#25]
commit 6b9685b overwrote updates from f9bbd5b -> Reverting documentation updates 😅 (mostly syntax stuff)

**Comment by adamdriscoll** [comment]
WTF - Sorry about that. I usually edit on GitBook and it looks like their merge process is messed up.

**Comment by adamdriscoll** [comment]
Everything should be set to PowerShell once again. Sorry this happened and took so long to fix...
