### ISSUE TITLE
Visually Search for Icons - Update to code example

### ISSUE THREAD

**Issue by checkso** [ironmansoftware/universal-docs#26]
Just to make this piece a bit more easy, as I was looking for icons and couldn't find the name of it.

`
New-UDDashboard -Title "Hello, World!" -Content {
    New-UDTextbox -Id 'txtIconSearch' -Label 'Search' 
    New-UDButton -Text 'Search' -OnClick {
        Sync-UDElement -Id 'icons'
    }

    New-UDElement -tag 'p' -Content {}
   
    New-UDDynamic -Id 'icons' -Content {
            $Icons = [Enum]::GetNames([UniversalDashboard.Models.FontAwesomeIcons])
            $IconSearch = (Get-UDElement -Id 'txtIconSearch').value
            if ($null -ne $IconSearch -and $IconSearch -ne '')
            {
            $Icons = $Icons.where({ $_ -match $IconSearch})
        }
  
        foreach($icon in $icons) {
            New-UDChip -Label $icon -Icon (New-UDIcon -Icon $icon)
        }
    }
}
`

Changed is the following line: 

`
New-UDChip -Label $icon -Icon (New-UDIcon -Icon $icon)
`

**Comment by adamdriscoll** [comment]
Thanks! Updated.
