### ISSUE TITLE
New-UDEndpointSchedule correction

### ISSUE THREAD

**Issue by MarekITPro** [ironmansoftware/universal-docs#3]
_Startup: Cannot bind argument to parameter 'Schedule' because it is null._ 
This error comes up when starting UD with the following code pasted from the documentation:
`$EndpointSchedule = New-UDEndpointSchedule -Every 10 -Minute
$Endpoint = New-UDEndpoint -Schedule $Schedule -Endpoint {} `

I think the -Schedule should be set to: $EndpointSchedule, not $Schedule which is not defined.

**Comment by adamdriscoll** [comment]
Thanks! This has been fixed.
