### ISSUE TITLE
Differences between Local and Remote Universal Instance with VS Code Extension

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/universal-docs#32]
I think explaining the differences (limitations etc.) between connecting with a Local or Remote Universal Instance with the [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ironmansoftware.powershell-universal) should be done. The experience doesn't seem to be the same (Eg: debugging). These differences should be documented.

https://docs.powershelluniversal.com/get-started/visual-studio-code-extension

@adamdriscoll

**Comment by adamdriscoll** [comment]
I've updated the docs to include more info here: https://docs.powershelluniversal.com/visual-studio-code-extension
