### ISSUE TITLE
Endpoints: CWE-914 Warning

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/universal-docs#35]
https://github.com/ironmansoftware/universal-docs/blob/master/api/endpoints.md#query-string-parameters should come with a warning regarding [CWE-914: Improper Control of Dynamically-Identified Variables](https://cwe.mitre.org/data/definitions/914.html) in order to promote good security practice:

Example of CWE-914:
```powershell
New-PSUEndpoint -Url "/api/v1.0/CWE914Test" -Description "Vulnerable to CWE-914" -Endpoint {
	if($ChallengeInputData -eq "AcceptableInput") {
		$IsChallengePassed = $true
	}
	if($IsChallengePassed) {
		"Challenge passed. Here is Sensitive Information"
	} else {
		"Challenge not passed"
	}
}
```
Challenge is bypassed by `http://localhost:5000/api/v1.0/CWE914Test?IsChallengePassed=1`

Remediation by using https://github.com/ironmansoftware/universal-docs/blob/master/api/endpoints.md#param-block :
```powershell
New-PSUEndpoint -Url "/api/v1.0/CWE914Test" -Description "Not Vulnerable to CWE-914" -Endpoint {
	Param(
		$ChallengeInputData
	)
	if($ChallengeInputData -eq "AcceptableInput") {
		$IsChallengePassed = $true
	}
	if($IsChallengePassed) {
		"Challenge passed. Here is Sensitive Information"
	} else {
		"Challenge not passed"
	}
}
```

@adamdriscoll

**Comment by Viajaz** [comment]
@adamdriscoll This is a relatively quick and easy win (doc change) that could prevent some nasty security surprises for PSU dev-users.

**Comment by adamdriscoll** [comment]
@Viajaz - Thanks for the examples and info. I've added it to the docs.
