### ISSUE TITLE
Ambiguous Information for Secret Variables

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/universal-docs#36]
https://github.com/ironmansoftware/universal-docs/blob/master/platform/variables.md#creating-a-secret-variable

> Values for secrets are stored within the current user's Windows Credential Manager instance. If you change users (such as running as a service account), the account will not have access to the previous user's secrets and you will need to add those secrets again.

This is a little bit ambiguous, what is the 'current user' in this context? The security principal of the Universal Windows Service? The security principal of the runspace (Eg: The Credential of a Automation Script, 'Run As' of a Dashboard, and the Windows Service for API Endpoints).

Given the Web UI does not prompt for credentials when adding a Secret Variable, one assumes it's the former of the above and then the secret is transferred into the runspace? I think these issues could be clarified.

@adamdriscoll

**Comment by adamdriscoll** [comment]
Thanks. Completed.
