### ISSUE TITLE
Add documentation for onClick event handlers

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/universal-docs#45]
https://forums.ironmansoftware.com/t/new-udicon-onclick/8219/4?u=omzig

**Comment by Omzig** [comment]
#AssignToMe

**Comment by Omzig** [comment]
- https://docs.powershelluniversal.com/userinterfaces/dashboards/components/element

**Comment by adamdriscoll** [comment]
I just realized that this was merged into the wrong branch (master) when it should have been v3. This has been fixed and the doc should now be live. I've also updated the default branch for this repo to be v3. 

https://docs.powershelluniversal.com/userinterfaces/dashboards/components/element#setting-attributes
