### ISSUE TITLE
Docs for running-as-a-service-account missing the HOW

### ISSUE THREAD

**Issue by wsuhoey** [ironmansoftware/universal-docs#9]
https://docs.ironmansoftware.com/config/running-as-a-service-account

This page says what to configure for permissions of the service account.
But the page lacks HOW to set Universal Dashboard to use the service account.

For example, by default the dashboard seems to use `NT AUTHORITY\SYSTEM` as the account to run as (determined via `whoami` or `([System.Security.Principal.WindowsIdentity]::GetCurrent()).Name`.

Again, this page doesn't tell me HOW to tell the UD to NOT run as `NT AUTHORITY\SYSTEM` and to instead run as a specified Service Account.

**Comment by nqui** [comment]
@wsuhoey I believe its a matter of fulfilling the prerequisite configs/settings in the Local Security Policy, and then going to `services.msc`, opening properties for the `PowerShell Universal` service, open the `Log On` tab, and enter the credentials for your service account. 

Someone else please correct me if I'm wrong! I've done the above and have my PowerShell Universal instance, as well as dashboards running under my service account.

**Comment by adamdriscoll** [comment]
This is correct. I will update the documentation to include that information.
